apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: docker-build
  namespace: default
  labels:
    name: docker-build
spec:
  triggers:
  # - type: GitHub
  #   github:
  #     secret: secret-token
  - type: ImageChange
    imageChange: {}
  - type: ConfigChange
  source:
    type: Git
    git:
      uri: https://github.com/davidruedasalas/openshift-java-spring-boot.git
      ref: main # or specify branch, tag, or commit hash
      contextDir: Dockerfile # Path to the directory containing the Dockerfile
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: hello-java:latest
